theme: jekyll-theme-cayman

title: Heta specifications
email: dev@insysbio.com
description: >-
  Domain specific programming language for QSP and SB modeling
baseurl: / # the subpath of your site, e.g. /blog
url: "https://hetalang.github.io/heta-specifications/"
logo: /assets/img/logo.png

plugins:
  - jekyll-feed
  - jekyll-seo-tag
yandex_metrika: 55703665 # not implemented in theme layout
google_analytics: UA-149749027-1
github_username:  metelkin
social:
  name: InSysBio
  links:
    - https://www.facebook.com/insysbio
    - https://www.linkedin.com/insysbio
    - https://github.com/insysbio
    - https://hetalang.github.io/
    
