name: Commit to hetalang.github.io

on:
  push:
    branches:
      - master
      - vite-press

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hetalang/hetalan.github.io
        uses: actions/checkout@v4
        with:
          repository: hetalang/hetalang.github.io
          ref: vite-press
          path: hetalang.github.io

      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          path: heta-specifications

      - name: Display all files
        run: |
          echo "Current directory:"
          pwd
          echo "Listing all files:"
          ls -R .

      - name: Copy files to hetalang.github.io
        run: |
          echo "Copying files to hetalang.github.io..."
          cp -r heta-specifications/docs/* hetalang.github.io/docs/
